### ISSUE TITLE
ChainingHints from other files are sometimes displayed

### ISSUE THREAD

**Issue by TimoFreiberg** [fannheyward/coc-rust-analyzer#228]
Not completely sure how to reproduce this yet, but I sometimes get ChainingHints in file A that match file B

Wrong hint at line 205 in display.rs:
![image](https://user-images.githubusercontent.com/5281645/80866907-9c617280-8c91-11ea-85bb-29b03b1c4b0a.png)
Same hint is correct at line 205 in add_function.rs:
![image](https://user-images.githubusercontent.com/5281645/80866933-b8fdaa80-8c91-11ea-8f44-5f18275ac992.png)

I have these two buffers open:
![image](https://user-images.githubusercontent.com/5281645/80866949-c74bc680-8c91-11ea-900f-0ed4688f4283.png)

**Comment by lucasholder** [comment]
Same here

<img width="454" alt="Screen Shot 2020-05-06 at 5 28 30 AM" src="https://user-images.githubusercontent.com/62086489/81162167-bbdef080-8f5a-11ea-9aa4-7a28e2f634f3.png">

**Comment by iago-lito** [comment]
Same here, I can reproduce with these two files in different tabs:
`other_file.rs`
![in_the_good_file](https://user-images.githubusercontent.com/10091387/81734216-7a3ad200-9493-11ea-92d0-792275607104.png)

`main.rs`
![in_the_wrong_file](https://user-images.githubusercontent.com/10091387/81734266-89ba1b00-9493-11ea-92a2-806d1112e845.png)

Reproducing is a bit hard because I need to tinker a bit for the chaining hints to actually appear, but it is annoying when they do :\

**Comment by fannheyward** [comment]
I've released 0.6.4, and try to make a fix for this issue. Feedbacks are welcome.

**Comment by iago-lito** [comment]
@fannheyward Well, after `CocUpdate` and even reinstalling `coc-rust-analyzer`, I can read

`:CocList extensions`
![version_0 6 4](https://user-images.githubusercontent.com/10091387/81847306-b5043f00-9553-11ea-9fae-fc5bf816bcd7.png)

But the problem still occurs :'(

**Comment by fannheyward** [comment]
Try 0.6.5.

**Comment by iago-lito** [comment]
Well, it seems fixed now with 0.6.5, thanks a lot :heart:   
I like those chaining hints :)
